# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    install:
      - pip install . --group docs
sphinx:
  configuration: docs/conf.py
